name: Build and Push Docker Image
on:
  release:
    types:
      - 'published'

jobs:
  build:
    name: Build and Push Docker Image
    permissions: write-all
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        apps:
          - watcher
          - guard

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Move Config Files
        run: |
          mv docker/nginx.conf ./
          mv docker/entrypoint.sh ./
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: arsalanyavari
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata action
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/arsalanyavari/ui-${{ matrix.apps }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          target: ${{ matrix.apps }}

      - name: stage 2
        run: echo "what will happen?"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: arsalanyavari
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          target: ${{ matrix.apps }}

#           platforms: linux/amd64,linux/arm64,linux/arm/v7
