name: Build and Push Docker Image
on:
  release:
    types:
      - 'published'

jobs:
  build:
    name: Build and Push Docker Image
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          - latest
          - ${{ github.ref_name }}
        apps:
          - watcher
          - guard

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Move Config Files
        run: |
          mv docker/nginx.conf ./
          mv docker/entrypoint.sh ./

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: arsalanyavari
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          docker buildx build --platform=linux/amd64,linux/arm/v6,linux/arm64 -t ghcr.io/arsalanyavari/ui-${{ matrix.apps }}:${{ matrix.versions }} --target=${{ matrix.apps }} --push .
        # docker push ghcr.io/arsalanyavari/ui-${{ matrix.apps }}:${{ matrix.versions }}
          
        # uses: docker/build-push-action@v4
        # with:
        #   context: .
        #   platforms: linux/amd64,linux/arm64,linux/arm/v7
        #   push: true
        #   tags: ghcr.io/arsalanyavari/ui-${{ matrix.apps }}:${{ matrix.versions }}
        #   target: ${{ matrix.apps }}
